paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos se recuperan correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductData'
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          description: ID del producto a obtener
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto obtenido correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    put:
      summary: Actualiza un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          description: ID del producto a actualizar
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductData'
      responses:
        "200":
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          description: ID del producto a eliminar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID generado por mongo
        id:
          type: integer
          description: Un id interno de productos
        title:
          type: string
          description: El nombre del producto
        description:
          type: string
          description: La descripción detallada del producto
        price:
          type: number
          description: Precio del producto
        code:
          type: string
          description: Alfanumérico que es único entre los productos (_id también es único)
        stock:
          type: integer
          description: Cantidad de este producto disponible
        status:
          type: boolean
          description: Un true o un false, esto activa o desactiva el producto a la hora de leerlo en /products
        thumbnails:
          type: array
          description: Array que contiene las direcciones o enlaces a imágenes de productos
          items:
            type: string
    ProductData:
      type: object
      properties:
        id:
          type: integer
          description: Un id interno de productos
        title:
          type: string
          description: El nombre del producto
        description:
          type: string
          description: La descripción detallada del producto
        price:
          type: number
          description: Precio del producto
        code:
          type: string
          description: Alfanumérico que es único entre los productos (_id también es único)
        stock:
          type: integer
          description: Cantidad de este producto disponible
        status:
          type: boolean
          description: Un true o un false, esto activa o desactiva el producto a la hora de leerlo en /products
        thumbnails:
          type: array
          description: Array que contiene las direcciones o enlaces a imágenes de productos
          items:
            type: string
